### ISSUE TITLE
Should this just be a page on Botwiki.org?

### ISSUE THREAD

**Issue by stefanbohacek** [botwiki/open-source-bots#1]
Eg. botwiki.org/opensource-bots.

**Comment by coleww** [comment]
is editing botwiki as easy as a PR? 

makes sense if most of the bot codes are on github too

**Comment by stefanbohacek** [comment]
Yes, you can just do a PR to https://github.com/botwiki/botwiki.org.

The bigger points are:
- Botwiki.org doesn't allow browsing multiple tags at once (yet), so you can't easily see only opensourced Twitter bots
- Botwiki.org doesn't _necessarily_ aim to list all online bots, but there should be a list of _all_ open source bots

So I'd say there are three options, really.
1. Add every single bot to the site and change the Pico tag plugin to allow browsing by multiple tags.
2. Move the content of this repo to botwiki.org/opensource-bots
3. Add the more notable bots to Botwiki and maintain a separate list -- this repo (this is the current situation)

I didn't really want to end up with a site like http://botdb.gameology.org/bot-list, which has tons of bots, but is hard to really browse. I am not a huge fan of needing to add some of the open source bots to both Botwiki and to this separate repo.

I guess another option would be to have http://botwiki.org/tag/opensource and this repo could only have the bots that "didn't make the cut"? Honestly, I am not a huge fan of that either, because then you have to search through two different places. Plus some of the source code are not active bots, for example https://github.com/hugovk/word-tools. How would you add that to the site?

**Comment by coleww** [comment]
yeah, being able to browse like "reply bots" or "image bots" and get code that is workable would be really nice. That could be part of the selection/curation for the main site, is find strong example code for different archetypes of bots, and let people dig deeper if they want to. 

also, example code for bots that integrate different APIs/libraries. image-bots that use canvas vs. image-bots that use imagemagick (:O i wonder if this could be done programmatically by looking at the dependencies for the bots listed here?)

**Comment by stefanbohacek** [comment]
@coleww So I implemented the "multi-tag browsing", eg http://botwiki.org/tag/opensource+ruby now works.

I decided to move all the open-source bots to Botwiki. This will actually work perfectly, because I can, for example, just add https://github.com/hugovk/word-tools as a separate "page" in the "content" folder, it just won't be tagged with "twitterbot", only something like "opensource" and "twitter", "python", etc.

Then I can easily link to "pages" tagged with multiple tags to sort of create a "category".

**Comment by stefanbohacek** [comment]
I will close this issue once the migration is over, but the answer is: [Yes](https://www.botwiki.org/tag/twitter+opensource)!

**Comment by stefanbohacek** [comment]
All the updates necessary for the merge are in place. The search is really awesome now, compare [this](https://botwiki.org/search?q=python+ruby) vs [this](https://botwiki.org/search?q=python+OR+ruby)!

**Comment by stefanbohacek** [comment]
@coleww This is finally starting to come together with https://www.botwiki.org/tag/opensource and  https://www.botwiki.org/tag/opensource+twitterbot.

Now we just need more and more bots.
